sudo: true
language: node_js
node_js:
  - "10"
  - "8"
python:
  - "3.7"
  - "3.6"
install:
  - sudo bash install_debian_script.sh
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade virtualenv
  - make
  - yarn install
script:
  - make test
after_success: 'yarn run coveralls'