language: node_js
node_js:
  - "10"
  - "9"
  - "7"
python:
  - "3.7"
  - "3.6"
install:
  - pip3 install --upgrade pip
  - pip3 install --upgrade virtualenv
  - make
  - yarn install
script:
  - make test